# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stskeygen < Formula
  desc "A commandline utility for trading directory service credentials (such as AD username and password) for AWS STS Keys."
  homepage "https://cimpress-support.atlassian.net/wiki/spaces/CloudKB/pages/15058567646/Generating+STS+access+keys+via+Auth0"
  version "3.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://ce-installation-binaries.s3.us-east-1.amazonaws.com/stskeygen/3.1.2/stskeygen_3.1.2_darwin_amd64.tar.gz"
      sha256 "2a35bab853479d4cbc8c7c88da11df2bf6fc2ceadb45043c93256711f0029951"

      def install
        bin.install "stskeygen"
      end
    end
    if Hardware::CPU.arm?
      url "https://ce-installation-binaries.s3.us-east-1.amazonaws.com/stskeygen/3.1.2/stskeygen_3.1.2_darwin_arm64.tar.gz"
      sha256 "b0d924a1c46d433df3ff10fafc422abdebcfc1cd28da8d886b50600d36bc9e9a"

      def install
        bin.install "stskeygen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://ce-installation-binaries.s3.us-east-1.amazonaws.com/stskeygen/3.1.2/stskeygen_3.1.2_linux_amd64.tar.gz"
      sha256 "d435e258e2ba27d78a0d02c707f408d8bec534fe1ef9671aff3d130ed8404517"
      def install
        bin.install "stskeygen"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://ce-installation-binaries.s3.us-east-1.amazonaws.com/stskeygen/3.1.2/stskeygen_3.1.2_linux_arm64.tar.gz"
      sha256 "fff5378cd1f9197c5d8555551be8a98986c0d87551cf9beeeed11371f3680c24"
      def install
        bin.install "stskeygen"
      end
    end
  end

  test do
    system "#{bin}/stskeygen"
  end
end
